modules:
  jira:globalPage:
    - key: forge-sandbox
      resource: web
      resolver:
        function: resolver
      layout: basic
      title: Forge Sandbox
  function:
    - key: resolver
      handler: index.handler
resources:
  - key: web
    path: web
permissions:
  content:
    styles:
      # this seems to be necessary for react apps
      - unsafe-inline

