modules:
  jira:globalPage:
    - key: forge-sandbox
      resource: web
      resolver:
        function: resolver
      layout: basic
      title: Forge Sandbox
  function:
    - key: resolver
      handler: index.handler
resources:
  - key: web
    path: web
