modules:
  jira:projectPage:
    - key: dashboard
      resource: web
      resolver:
        function: resolver
      title: dashboard
  function:
    - key: resolver
      handler: index.handler
resources:
  - key: web
    path: web
