name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - uses: jaid/action-npm-install@v1.2.4
    - run: npm run lint
    - run: npm test
    - run: npm run build
